# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170219_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
