# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170220_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False)),
                ('memory', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
