# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='extra_img_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='extra_img_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
