# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170221_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField()),
                ('visited', models.BooleanField(default=False)),
                ('memory', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Blurb',
        ),
    ]
