# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170221_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
