# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170221_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default=''),
        ),
    ]
